apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-flask
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: name
          image: adamcao/helloflaskredis:2.0
          ports:
            - containerPort: 5001
---
kind: Service
apiVersion: v1
metadata:
  name: hello-flask
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - name: helloflask
      port: 5000
      targetPort: 5001
